"""Added lot in Bien table

Revision ID: 29a54feacd9d
Revises: 9b22dddc60d0
Create Date: 2025-11-04 22:32:44.269582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a54feacd9d'
down_revision: Union[str, Sequence[str], None] = '9b22dddc60d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bien', schema=None) as batch_op:
        batch_op.drop_column('lot')

    # ### end Alembic commands ###
