"""Modification des types char en varchar

Revision ID: 340ef9025c19
Revises: a200b1a91ed9
Create Date: 2025-10-31 18:38:16.483167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340ef9025c19'
down_revision: Union[str, Sequence[str], None] = 'a200b1a91ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bien', schema=None) as batch_op:
        batch_op.alter_column('id_bien',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('commune', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=50), nullable=False))
        batch_op.alter_column('id_departement',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False)

    with op.batch_alter_table('departement', schema=None) as batch_op:
        batch_op.alter_column('id_departement',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False)

    with op.batch_alter_table('type_voie', schema=None) as batch_op:
        batch_op.alter_column('voie',
               existing_type=sa.CHAR(length=5),
               type_=sa.String(length=5),
               existing_nullable=False)

    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.alter_column('id_bien',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.alter_column('id_bien',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('type_voie', schema=None) as batch_op:
        batch_op.alter_column('voie',
               existing_type=sa.String(length=5),
               type_=sa.CHAR(length=5),
               existing_nullable=False)

    with op.batch_alter_table('departement', schema=None) as batch_op:
        batch_op.alter_column('id_departement',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False)

    with op.batch_alter_table('commune', schema=None) as batch_op:
        batch_op.alter_column('id_departement',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False)
        batch_op.drop_column('nom')

    with op.batch_alter_table('bien', schema=None) as batch_op:
        batch_op.alter_column('id_bien',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
