"""Remove adresse

Revision ID: 826d889d16ec
Revises: fe35238ce2e3
Create Date: 2025-11-06 22:48:47.413505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826d889d16ec'
down_revision: Union[str, Sequence[str], None] = 'fe35238ce2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_voie')
    op.drop_table('adresse')
    with op.batch_alter_table('bien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_commune', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'commune', ['id_commune'], ['id_commune'])
        batch_op.drop_column('id_adresse')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_adresse', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'adresse', ['id_adresse'], ['id_adresse'])
        batch_op.drop_column('id_commune')

    op.create_table('adresse',
    sa.Column('id_adresse', sa.INTEGER(), nullable=False),
    sa.Column('id_commune', sa.INTEGER(), nullable=False),
    sa.Column('numero_voie', sa.INTEGER(), nullable=True),
    sa.Column('nom_voie', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id_voie', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_commune'], ['commune.id_commune'], ),
    sa.ForeignKeyConstraint(['id_voie'], ['type_voie.id_voie'], ),
    sa.PrimaryKeyConstraint('id_adresse')
    )
    op.create_table('type_voie',
    sa.Column('id_voie', sa.INTEGER(), nullable=False),
    sa.Column('voie', sa.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id_voie')
    )
    # ### end Alembic commands ###
