"""Modification pour domtom

Revision ID: a200b1a91ed9
Revises: d56be8b7553e
Create Date: 2025-10-31 18:25:07.572786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a200b1a91ed9'
down_revision: Union[str, Sequence[str], None] = 'd56be8b7553e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commune', schema=None) as batch_op:
        batch_op.alter_column('id_departement',
               existing_type=sa.INTEGER(),
               type_=sa.CHAR(length=3),
               existing_nullable=False)
        batch_op.alter_column('code_postal',
               existing_type=sa.CHAR(length=5),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('code_insee',
               existing_type=sa.CHAR(length=5),
               type_=sa.String(length=6),
               existing_nullable=False)

    with op.batch_alter_table('departement', schema=None) as batch_op:
        batch_op.alter_column('id_departement',
               existing_type=sa.INTEGER(),
               type_=sa.CHAR(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departement', schema=None) as batch_op:
        batch_op.alter_column('id_departement',
               existing_type=sa.CHAR(length=3),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('commune', schema=None) as batch_op:
        batch_op.alter_column('code_insee',
               existing_type=sa.String(length=6),
               type_=sa.CHAR(length=5),
               existing_nullable=False)
        batch_op.alter_column('code_postal',
               existing_type=sa.String(length=5),
               type_=sa.CHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('id_departement',
               existing_type=sa.CHAR(length=3),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
