"""Remove code postal

Revision ID: a9a1e1f18175
Revises: 340ef9025c19
Create Date: 2025-11-03 22:29:35.559971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a1e1f18175'
down_revision: Union[str, Sequence[str], None] = '340ef9025c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commune', schema=None) as batch_op:
        batch_op.drop_column('code_postal')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commune', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_postal', sa.VARCHAR(length=5), nullable=True))

    # ### end Alembic commands ###
