"""...

Revision ID: d56be8b7553e
Revises: 
Create Date: 2025-10-30 22:55:33.776423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56be8b7553e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_region')
    )
    op.create_table('type_voie',
    sa.Column('id_voie', sa.Integer(), nullable=False),
    sa.Column('voie', sa.CHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id_voie')
    )
    op.create_table('departement',
    sa.Column('id_departement', sa.Integer(), nullable=False),
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['region.id_region'], ),
    sa.PrimaryKeyConstraint('id_departement')
    )
    op.create_table('commune',
    sa.Column('id_commune', sa.Integer(), nullable=False),
    sa.Column('id_departement', sa.Integer(), nullable=False),
    sa.Column('code_commune', sa.Integer(), nullable=False),
    sa.Column('code_postal', sa.CHAR(length=5), nullable=True),
    sa.Column('code_insee', sa.CHAR(length=5), nullable=False),
    sa.ForeignKeyConstraint(['id_departement'], ['departement.id_departement'], ),
    sa.PrimaryKeyConstraint('id_commune')
    )
    op.create_table('adresse',
    sa.Column('id_adresse', sa.BigInteger(), nullable=False),
    sa.Column('id_commune', sa.Integer(), nullable=False),
    sa.Column('numero_voie', sa.Integer(), nullable=True),
    sa.Column('nom_voie', sa.String(length=100), nullable=True),
    sa.Column('id_voie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_commune'], ['commune.id_commune'], ),
    sa.ForeignKeyConstraint(['id_voie'], ['type_voie.id_voie'], ),
    sa.PrimaryKeyConstraint('id_adresse')
    )
    op.create_table('bien',
    sa.Column('id_bien', sa.Integer(), nullable=False),
    sa.Column('id_adresse', sa.BigInteger(), nullable=False),
    sa.Column('btq', sa.String(length=5), nullable=True),
    sa.Column('nombre_pieces', sa.Integer(), nullable=False),
    sa.Column('surface_carrez', sa.Float(), nullable=False),
    sa.Column('surface_local', sa.Integer(), nullable=False),
    sa.Column('type_bien', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_adresse'], ['adresse.id_adresse'], ),
    sa.PrimaryKeyConstraint('id_bien')
    )
    op.create_table('vente',
    sa.Column('id_vente', sa.BigInteger(), nullable=False),
    sa.Column('id_bien', sa.Integer(), nullable=False),
    sa.Column('date_vente', sa.Date(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_bien'], ['bien.id_bien'], ),
    sa.PrimaryKeyConstraint('id_vente')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vente')
    op.drop_table('bien')
    op.drop_table('adresse')
    op.drop_table('commune')
    op.drop_table('departement')
    op.drop_table('type_voie')
    op.drop_table('region')
    # ### end Alembic commands ###
