"""Added population to commune

Revision ID: fe35238ce2e3
Revises: 29a54feacd9d
Create Date: 2025-11-05 23:53:48.447739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe35238ce2e3'
down_revision: Union[str, Sequence[str], None] = '29a54feacd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commune', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commune', schema=None) as batch_op:
        batch_op.drop_column('population')

    # ### end Alembic commands ###
